inherit_from:
  - https://raw.githubusercontent.com/cookpad/guides/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*
    - vendor/**/.*

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
RSpec/DescribedClass:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
